# Generated by Django 4.2.10 on 2024-03-06 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('entities', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic'),
        ),
        migrations.AddField(
            model_name='usertopic',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresource',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.resource'),
        ),
        migrations.AddField(
            model_name='userresource',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='supported_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported', to='entities.organization'),
        ),
        migrations.AddField(
            model_name='support',
            name='supported_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported', to='authentication.supportentitytype'),
        ),
        migrations.AddField(
            model_name='support',
            name='supporter_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='entities.organization'),
        ),
        migrations.AddField(
            model_name='support',
            name='supporter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='authentication.supportentitytype'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
