# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: frontend/app
i18n-dir: frontend/i18n/locales
i18n-src: frontend/i18n/locales/en-US.json

file-types-to-check: [.js, .ts, .vue]

checks:
  # Global configurations are applied to all checks.
  global:
    active: True
  missing-keys:
    active: False
  alt-texts:
    active: False
