env:
  contexts:
  - name: activist-org-en
    urls:
    - https://www.activist.org/en/
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  # Use a spider as the standard approach.
  - type: spider
    parameters:
      context: activist-org-en
      maxDuration: 10
      maxDepth: 10

  # AJAX spider for dynamic content.
  - type: spiderAjax
    parameters:
      context: activist-org-en
      maxDuration: 10
      maxCrawlDepth: 10
      browserId: firefox-headless

  # Passive Scan - Waits for spiders/other actions.
  - type: passiveScan-wait
    parameters:
      maxDuration: 60

  # Active Scan - using proper policy configuration.
  - type: activeScan
    parameters:
      context: activist-org-en
      policy:
        strength: HIGH
        threshold: MEDIUM

  # Reporting (JSON Summary) - Using reports directory for writing.
  - type: outputSummary
    parameters:
      summaryFile: /zap/reports/zap_summary.json

  # Alert Filtering with proper format according to documentation.
  - type: alertFilter
    parameters:
      deleteGlobalAlerts: true
    alertFilters:
      - ruleId: 10016
        newRisk: "False Positive"
      - ruleId: 10020
        newRisk: "False Positive"
      - ruleId: 10021
        newRisk: "False Positive"
      - ruleId: 10038
        newRisk: "False Positive"
      - ruleId: 10063
        newRisk: "False Positive"
      - ruleId: 90022
        newRisk: "False Positive"
      - ruleId: 10049
        newRisk: "False Positive"
      - ruleId: 10109
        newRisk: "False Positive"
      - ruleId: 10096
        newRisk: "False Positive"
      - ruleId: 10055
        newRisk: "False Positive"
      - ruleId: 40032
        newRisk: "False Positive"
      - ruleId: 2
        newRisk: "False Positive"
      - ruleId: 10202
        newRisk: "False Positive"
      - ruleId: 10104
        newRisk: "False Positive"

  # Reporting (HTML Report) - Standardized path and filename.
  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/reports
      reportFile: report_html.html
      reportTitle: ZAP Scan Report (Automation Framework)
      reportDescription: 'Generated by ZAP Automation Framework'
