# Generated by Django 4.2 on 2023-10-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicformat',
            name='format_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.format'),
        ),
        migrations.AddField(
            model_name='topicformat',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic'),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.resource'),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic'),
        ),
    ]
