<template>
  <div class="bg-layer-0 overflow-hidden">
    <Head>
      <Title>{{ $t("pages.index.title") }}</Title>
    </Head>
    <LandingSplash />
    <LandingCommunityBanner />
    <div
      class="mb-2 mt-4 flex flex-col sm:mb-4 sm:mt-10 xl:mb-8 xl:mt-16 2xl:mb-12 2xl:mt-24"
    >
      <LandingContent
        contentPosition="left"
        header="pages.index.get_active"
        tagline="pages.index.get_active_tagline"
        text="pages.index.get_active_text"
        :imgUrl="GET_ACTIVE_IMAGE_URL"
        imageAltText="pages.index.get_active_img_alt_text"
        btnText1="pages.index.learn_more"
        btnUrl1="https://docs.activist.org/activist"
        btnAriaLabel1="pages.index.get_active_aria_label"
        btnId1="btn-get-active"
      />
      <LandingContent
        contentPosition="right"
        header="pages.index.get_organized"
        tagline="pages.index.get_organized_tagline"
        text="pages.index.get_organized_text"
        :imgUrl="GET_ORGANIZED_IMAGE_URL"
        imageAltText="pages.index.get_organized_img_alt_text"
        btnText1="pages.index.learn_more"
        btnUrl1="https://docs.activist.org/activist"
        btnAriaLabel1="pages.index.get_organized_aria_label"
        btnId1="btn-get-organized"
      />
      <LandingContent
        contentPosition="left"
        header="pages.index.grow_organization_header"
        tagline="pages.index.grow_organization_tagline"
        text="pages.index.grow_organization_text"
        :imgUrl="GROW_ORGANIZATION_IMAGE_URL"
        imageAltText="pages.index.grow_organization_img_alt_text"
        btnText1="pages.index.learn_more"
        btnUrl1="https://docs.activist.org/activist"
        btnAriaLabel1="pages.index.grow_organization_aria_label"
        btnId1="btn-grow-organization"
      />
      <LandingTechBanner />
      <LandingContent
        contentPosition="right"
        header="pages.index.about_us"
        tagline="pages.index.activist_section_tagline"
        text="pages.index.activist_section_text"
        imgUrl="/icons/activist/activist_icon"
        imageAltText="_global.activist_icon_img_alt_text"
        btnText1="pages.index.learn_more"
        btnUrl1="https://docs.activist.org/activist"
        btnAriaLabel1="pages.index.activist_section_btn_aria_label"
        btnId1="btn-activist"
      />
      <LandingContent
        contentPosition="top"
        header="pages.index.our_supporters"
        tagline="pages.index.our_supporters_tagline"
        text="pages.index.our_supporters_text"
        imageAltText=""
        btnText1="pages.index.become_supporter"
        btnUrl1="/supporters/join"
        btnAriaLabel1="pages.index.our_supporters_btn_become_aria_label"
        btnText2="pages.index.view_all_supporters"
        btnUrl2="https://docs.activist.org/activist/organization/community/supporters"
        btnAriaLabel2="pages.index.our_supporters_btn_view_aria_label"
        subText="pages.index.our_supporters_sub_text"
        btnId1="btn-become-supporter"
        btnId2="btn-our-supporters"
      />
    </div>
  </div>
</template>
