name: 🎨 Design improvement
description: Make a suggestion for activist's UX/UI designs.
labels: ["design"]
projects: ["activist-org/1"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
          required: true
        - label: I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A brief description of the enhancement you propose (with screenshots if applicable).
    validations:
      required: true
  - type: textarea
    id: contribution
    attributes:
      label: Contribution
      placeholder: Let us know if you'd like to help and how :)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion!
