name: ✨ Feature request
description: Have a new idea or feature for activist? Please suggest!
labels: ["feature"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
          required: true
        - label: I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A brief description of the enhancement you propose (with screenshots if applicable).
    validations:
      required: true
  - type: textarea
    id: contribution
    attributes:
      label: Contribution
      placeholder: Let us know if you'd like to help and how :)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion!
