// SPDX-License-Identifier: AGPL-3.0-or-later
export enum TopicEnum {
  ACCESSIBILITY = "ACCESSIBILITY",
  ANIMAL_RIGHTS = "ANIMAL_RIGHTS",
  DEMOCRACY_AND_GOVERNANCE = "DEMOCRACY_AND_GOVERNANCE",
  EDUCATION = "EDUCATION",
  EMERGENCY_RELIEF = "EMERGENCY_RELIEF",
  ENVIRONMENT = "ENVIRONMENT",
  HEALTH = "HEALTH",
  HOUSING = "HOUSING",
  LABOR_RIGHTS = "LABOR_RIGHTS",
  LGBTQIA = "LGBTQIA",
  PEACE_AND_RESOLUTION = "PEACE_AND_RESOLUTION",
  RACIAL_JUSTICE = "RACIAL_JUSTICE",
  REFUGEES_AND_MIGRATION = "REFUGEES_AND_MIGRATION",
  TECHNOLOGY_AND_PRIVACY = "TECHNOLOGY_AND_PRIVACY",
  WOMENS_RIGHTS = "WOMENS_RIGHTS",
}
