<template>
  <div
    class="grid grid-cols-1 gap-6 sm:grid-rows-2 sm:grid-cols-2 md:grid-rows-1 md:grid-cols-3 lg:gap-12"
  >
    <LandingPageLogoImage
      imageName="WikimediaDE"
      imageLink="https://www.wikimedia.de"
      aria-label="$t(wikimedia-de-logo-label)"
    />
    <LandingPageLogoImage
      imageName="WikimediaRS"
      imageLink="https://wikimedia.rs"
      aria-label="$t(wikimedia-rs-logo-label)"
    />
    <LandingPageLogoImage
      imageName="ImpactHub"
      imageLink="https://belgrade.impacthub.net"
      aria-label="$t(impacthub-belgrade-logo-label)"
    />
  </div>
</template>
