name: audit_packages
on:
  schedule:
    - cron: "0 0 15 */1 *"
  workflow_dispatch:

jobs:
  check-repository:
    runs-on: ubuntu-latest
    outputs:
      is_remote_main: ${{ steps.check.outputs.is_remote_main }}
    steps:
      - name: Check repository
        id: check
        run: |
          if [ "$GITHUB_REPOSITORY" = "activist-org/activist" ]; then
            echo "is_remote_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_remote_main=false" >> "$GITHUB_OUTPUT"
            echo "::warning::This workflow should only run in activist-org/activist repository."
          fi

  setup_project:
    needs: check-repository
    if: needs.check-repository.outputs.is_remote_main == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Node Environment
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Initialize Report
        run: |
          echo "# Packages Audit Report $(date '+%B %d, %Y')" > reports.md

      - name: Setup Yarn
        working-directory: ./frontend
        continue-on-error: true
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install Frontend Dependencies
        id: install-frontend
        working-directory: ./frontend
        continue-on-error: true
        run: |
          rm -rf .yarn .pnp.* yarn.lock node_modules
          yarn set version 4.6.0
          yarn install --no-immutable

      - name: Set up Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        working-directory: ./backend
        run: uv sync --frozen --all-groups

      - name: Audit backend
        working-directory: ./backend
        run: |
          echo -e "Backend dependency Audit Report\n" >> ../report.md
          pysentry-rs | sed 's/\x1b\[[0-9;]*m//g' >> ../report.md

      - name: Audit frontend
        working-directory: ./frontend
        run: |
          echo -e "Frontend dependency Audit Report" >> ../report.md
          yarn npm audit --all >> ../report.md

      - name: Set date
        id: date
        run: echo "REPORT_DATE=$(date '+%B %d, %Y')" >> $GITHUB_ENV

      - name: Create GitHub Issue
        if: always()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Dependency Audit Report - ${{ env.REPORT_DATE }} 🤖"
          content-filepath: reports.md
          labels: |
            dependencies
            help wanted
            good first issue
