name: ci_frontend_vitest
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "frontend/**"
      - "!frontend/test-e2e"
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "!frontend/test-e2e"

jobs:
  frontend_tests:
    name: Run PR Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Setup Node environment
        uses: actions/setup-node@v5

      - name: Install dependencies via Yarn
        working-directory: ./frontend
        run: |
          corepack enable
          sudo yarn install

      - name: Run Vitest - Component Testing
        working-directory: ./frontend
        run: sudo yarn test --coverage --silent
