name: dependency_update_check
on:
  schedule:
    - cron: "0 0 15 */2 *"
  workflow_dispatch:

jobs:
  check-repository:
    runs-on: ubuntu-latest
    outputs:
      is_remote_main: ${{ steps.check.outputs.is_remote_main }}
    steps:
      - name: Check repository
        id: check
        run: |
          if [ "$GITHUB_REPOSITORY" = "activist-org/activist" ]; then
            echo "is_remote_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_remote_main=false" >> "$GITHUB_OUTPUT"
            echo "::warning::This workflow should only run in activist-org/activist repository."
          fi

  update_dependencies:
    needs: check-repository
    if: needs.check-repository.outputs.is_remote_main == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Node Environment
        uses: actions/setup-node@v7
        with:
          node-version: 24

      # MARK: Initialize

      - name: Initialize Report
        run: |
          echo "# Dependency Update Report $(date '+%B %d, %Y') 🤖📝" > reports.md
          echo "> [!NOTE]" >> reports.md
          echo "> Please note that all tests should pass for PRs that are updating dependencies. See [the local testing section of the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#local-testing) for more information on how to run tests before your PR." >> reports.md
          echo "## Available Updates ⚙️" >> reports.md

      # MARK: Frontend

      - name: Setup Yarn
        working-directory: ./frontend
        continue-on-error: true
        run: |
          sudo corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install Frontend Dependencies
        id: install-frontend
        working-directory: ./frontend
        continue-on-error: true
        run: |
          rm -rf .yarn .pnp.* yarn.lock node_modules
          yarn set version 4.6.0
          yarn install --no-immutable

      - name: Update Frontend Dependencies
        id: frontend-updates
        working-directory: ./frontend
        continue-on-error: true
        run: |
          cp package.json package.old.json
          npm install -g npm-check-updates

          echo -e "\n### Dependencies" >> ../reports.md
          echo -e "| Package Name | Old Version | New Available Version | Type |" >> ../reports.md
          echo -e "|--------------|-------------|-----------------------|------|" >> ../reports.md
          node ../utils/dependency_update_check/compare_frontend_versions.ts | sed 's/- \(.*\): \(.*\) → \(.*\)/| \1 | \2 | \3 | Frontend |/' >> ../reports.md || echo "No frontend changes found" >> ../reports.md

      # MARK: Backend

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Create Python Virtual Environment
        id: setup-venv
        working-directory: ./backend
        continue-on-error: true
        run: python -m venv .venv

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          uv sync --frozen --all-groups

      - name: Update Backend Dependencies
        id: backend-updates
        working-directory: ./backend
        continue-on-error: true
        run: |
          # Does uv the upgrade within the script so that we can parse the output.
          python ../utils/dependency_update_check/compare_backend_versions.py >> ../reports.md || echo "No backend changes found" >> ../reports.md

      # MARK: Run Tests

      - name: Run Frontend Tests
        id: frontend-tests
        working-directory: ./frontend
        continue-on-error: true
        run: |
          # Note: Don't check formatting.
          # echo "compare_versions.js" >> ../.prettierignore
          # echo -e "\n### Prettier Results" >> ../reports.md
          # echo "\`\`\`" >> ../reports.md
          # yarn prettier . --check --config ../.prettierrc --ignore-path ../.prettierignore 2>&1 | tee -a ../reports.md || true
          # echo "\`\`\`" >> ../reports.md

          echo -e "\n### ESLint Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          yarn lint 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

          echo -e "\n### Type Check Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          yarn typecheck 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

          echo -e "\n### Vitest Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          yarn test --silent 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

      - name: Add Test Results Header
        id: add-test-results-header
        continue-on-error: true
        run: |
          source .venv/bin/activate
          echo -e "\n## Test Results" >> ../reports.md

      - name: Run Backend Tests
        id: backend-tests
        working-directory: ./backend
        continue-on-error: true
        run: |
          # Note: Don't check formatting.
          # echo -e "\n### Ruff Format Results" >> ../reports.md
          # echo "\`\`\`" >> ../reports.md
          # ruff format . 2>&1 | tee -a ../reports.md || true
          # echo "\`\`\`" >> ../reports.md

          echo -e "\n### Ruff Lint Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          ruff check . 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

          echo -e "\n### mypy Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          mypy . --config-file pyproject.toml 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

          echo -e "\n### Pytest Results" >> ../reports.md
          echo "\`\`\`" >> ../reports.md
          pytest --cov=. --cov-report=term-missing --cov-fail-under=85 --cov-config=pyproject.toml -vv 2>&1 | tee -a ../reports.md || true
          echo "\`\`\`" >> ../reports.md

      # MARK: Create Issue

      - name: Set date
        id: date
        run: echo "REPORT_DATE=$(date '+%B %d, %Y')" >> $GITHUB_ENV

      - name: Create GitHub Issue
        if: always()
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: "Dependency Update Report - ${{ env.REPORT_DATE }} 🤖📝"
          content-filepath: reports.md
          labels: |
            dependencies
            help wanted
            good first issue
